[package]
name = "mutiny"
version = "0.0.1"
authors = ["Sam Clements <sam@borntyping.co.uk>"]

[lib]
name = "mutiny"

[[bin]]
name = "mutiny-memory"
path = "src/bin/memory.rs"

[[bin]]
name = "mutiny-announce"
path = "src/bin/mutiny-announce.rs"

[dependencies]
getopts = "0.2"
term = "0.1"

[dependencies.psutil]
git = "https://github.com/borntyping/rust-psutil"
