[package]
name = "mutiny"
version = "0.2.0"
license = "MIT"
authors = ["Sam Clements <sam@borntyping.co.uk>"]
description = "Some simple tools that can be used to test process monitoring systems"
repository = "https://github.com/borntyping/mutiny"

[dependencies]
docopt = "^0.6.39"
docopt_macros = "^0.6.39"
log = "^0.2.4"
psutil = "^0.3.0"
rustc-serialize = "^0.3.0"
simple_logger = "^0.1.0"
